#!/bin/bash

#iptables setup for routerpassword
#Author - Peter Wolf
#dougalite@gmail.com
#2-4-2025

#Attempts to block eveyrthing except router
#needs bash to run it not sh

sudo iptables -P FORWARD DENY
for i in {1..126} {128..191} {193..254}
	do
	        sudo iptables -A INPUT -s $i/8 -j DROP
        	sudo iptables -A INPUT -d $i/8 -j DROP
        	echo "Blocked $i"    
	done

